version: '3'

services:
  go-atcorder:
    container_name: go-atcorder
    ports:
      - 8000:8000
      - 5002:5002
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    environment:
      - GOPATH=/go
    volumes:
      # ホストOS：コンテナ側
      - ./:/go/src/github.com/birnamwood/go-atcorder/